name: Debug

on:
  workflow_dispatch:
    inputs:
      source:
        description: Source name
        required: true
        type: choice
        options:
          - goout
          - smsticket
          - ticketportal

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install .
      - run: echo "Debug source=${{ inputs.source }}"
